services:
  flows-app:
    image: flows-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    ports:
      - 8000:8000

  postgres:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5439:5432
    restart: always
    command: "postgres -c max_connections=150 -c shared_buffers=512MB -c effective_cache_size=1536MB -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=3495kB -c min_wal_size=1GB -c max_wal_size=4GB -c max_worker_processes=2 -c max_parallel_workers_per_gather=1 -c max_parallel_workers=2 -c max_parallel_maintenance_workers=1"
    env_file:
      - .env

  redis:
    image: redis:7.4.2-alpine
    command: redis-server  --requirepass $REDIS_PASSWORD
    ports:
      - 6379:6379
    restart: always
    env_file:
      - ".env"
    volumes:
      - data:/vol/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  celery:
    image: celery
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: celery -A src.core.worker worker --loglevel=INFO
    depends_on:
      - flows-app
      - redis

volumes:
  pgdata: {}
  data: {}
